version: 2.1

orbs:
  bun: ksylvest/bun@1.0.1

jobs:
  build:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - bun/install
      - run: bun install
      - run: bun run tauri build
      - run: ls

workflows:
  build:
    jobs:
      - build