version: 2.1

orbs:
  bun: ksylvest/bun@1.0.1
  node: circleci/node@5.2.0

jobs:
  build:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - bun/install
      - run: bun install
      - npm-run: tauri build
      - run: ls

workflows:
  build:
    jobs:
      - build